from . import res_company
from . import res_partner
from . import efr_location
from . import efr_cash_register
from . import efr_transactions
from . import account_invoice
from . import efr_invoice_term
from . import efr_invoice_term_line
from . import sale_subscription
